apiVersion: v1
kind: Service
metadata:
  name: clb-usrmgmt-restapp
  labels:
    app: usrmgmt-restapp
spec:
  type: LoadBalancer  # Default - CLB
  selector:
    app: usrmgmt-restapp
  ports:
  - port: 80
    targetPort: 8095



