apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermgmt-microservice
  labels:
    app: usermgmt-restapp
  namespace: dev3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-restapp
  template:
    metadata:
      labels:
        app: usermgmt-restapp
    spec:
      initContainers:
        - name: init-db
          image: busybox
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
      containers:
      - name: myausermgmt-restapppp
        image: stacksimplify/kube-usermanagement-microservice:1.0.0
        ports:
          - containerPort: 8095
        env:
          - name:  DB_HOSTNAME
            value: "mysql"
          - name: DB_PORT
            value: "3306"
          - name: DB_NAME
            value: "usermgmt"
          - name: DB_USERNAME
            value: "root"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db-password
                name: mysql-db-password 
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "1000m"  # 1000m is equal to 1Vcpu core
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - nc -z localhost 8095
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /usermgmt/health-status
            port: 8095
          initialDelaySeconds: 60
          periodSeconds: 30