apiVersion: v1
kind: Service
metadata:
  name: replicaset-nodeport-svc
spec:
  type: NodePort
  selector:
    app: myapp     # label of template in relica set
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30016
