apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-nodeport-svc
  laebls:
    app: myapp
spec:
  type: NodePort   # Load balancer, external name
  selector:
    app: myapp
  ports:
  - name: http
    port: 80  # service port
    targetPort: 80   # container port 
    nodePort: 30010  

